get-matrices:
	wget https://sparse.tamu.edu/MM/Bai/tub1000.tar.gz
	tar -zxvf tub1000.tar.gz
	wget https://sparse.tamu.edu/MM/LPnetlib/lp_truss.tar.gz 
	tar -zxvf lp_truss.tar.gz
	wget https://sparse.tamu.edu/MM/HB/bcspwr06.tar.gz
	tar -zxvf bcspwr06.tar.gz